version: '3.4'

services:
  ibmnodejscloudantapp:
    image: ibmnodejscloudantapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
      - 8080:8080
